<a href="https://colab.research.google.com/github/shoma1001/Summer_Training_2026_NIT_Patna/blob/main/RandomFClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import seaborn as sns
df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [57]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [58]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [59]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [60]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [61]:
df.time

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [62]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['time']=encoder.fit_transform(df['time'])

In [63]:
df.time.unique()

array([0, 1])

In [64]:
x=df.drop(labels=['time'],axis=1)
y=df['time']

In [65]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [66]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer#handle missing values
from sklearn.preprocessing import StandardScaler#feature scaling
from sklearn.preprocessing import OneHotEncoder#categorical to numerical
from sklearn.compose import ColumnTransformer

In [67]:
categorical_cols=['sex','smoker','day']
numerical_cols=['total_bill','tip','size']

In [68]:
#feature engineering automation
#numerical pipeline
num_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='median')),#missing value handled
        ('scaler',StandardScaler())
    ]

)
#categorical pipeline
cat_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('onehotencoder',OneHotEncoder())#categorical features to numerical
    ]
)

In [69]:
preprocessor=ColumnTransformer([
    ('num_pipeline',num_pipeline,numerical_cols)
    ,('cat_pipeline',cat_pipeline,categorical_cols)

])

In [70]:
from sklearn.model_selection import train_test_split

# Re-split to ensure x_train and x_test are DataFrames
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

x_train=preprocessor.fit_transform(x_train)
x_test=preprocessor.transform(x_test)

In [76]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [77]:
#model training automation
models={
    'Random Forest':RandomForestClassifier(),
    'Logistic Regression':LogisticRegression(),
    'Decision Tree':DecisionTreeClassifier()
}

In [78]:
from sklearn.metrics import accuracy_score

In [81]:
def evaluate_model(x_train,y_train,x_test,y_test,models):
  report={}
  for i in range(len(models)):
    model= list(models.values())[i]
    #train model
    model.fit(x_train,y_train)
    #predict testing data
    y_test_pred=model.predict(x_test)
    #get accuracy score for test data
    test_model_score=accuracy_score(y_test,y_test_pred)
    report[list(models.keys())[i]]=test_model_score

  return report

In [82]:
evaluate_model(x_train,y_train,x_test,y_test,models)

{'Random Forest': 0.9591836734693877,
 'Logistic Regression': 1.0,
 'Decision Tree': 0.9387755102040817}